/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CourseId = IDL.Nat;
export const Course = IDL.Record({
  'id' : CourseId,
  'region' : IDL.Text,
  'title' : IDL.Text,
  'artType' : IDL.Text,
  'description' : IDL.Text,
  'mentorName' : IDL.Text,
  'price' : IDL.Nat,
  'mentorBio' : IDL.Text,
});
export const StudentProgress = IDL.Record({
  'progressPercent' : IDL.Nat,
  'royaltiesEarned' : IDL.Nat,
  'courseId' : CourseId,
});
export const UserProfile = IDL.Record({
  'region' : IDL.Text,
  'name' : IDL.Text,
});
export const HeritageRegion = IDL.Record({
  'artForms' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
});
export const ArtworkId = IDL.Nat;
export const ArtworkStatus = IDL.Variant({
  'verified' : IDL.Null,
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Artwork = IDL.Record({
  'id' : ArtworkId,
  'status' : ArtworkStatus,
  'studentId' : IDL.Principal,
  'submittedAt' : IDL.Nat64,
  'image' : ExternalBlob,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCourse' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'enrollInCourse' : IDL.Func([CourseId], [], []),
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getCallerCoursesProgress' : IDL.Func(
      [],
      [IDL.Opt(IDL.Vec(StudentProgress))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoursesByRegion' : IDL.Func([IDL.Text], [IDL.Vec(Course)], ['query']),
  'getHeritageRegions' : IDL.Func([], [IDL.Vec(HeritageRegion)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVerifiedArtworks' : IDL.Func([], [IDL.Vec(Artwork)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitArtwork' : IDL.Func([ExternalBlob], [], []),
  'verifyArtwork' : IDL.Func([ArtworkId, ArtworkStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CourseId = IDL.Nat;
  const Course = IDL.Record({
    'id' : CourseId,
    'region' : IDL.Text,
    'title' : IDL.Text,
    'artType' : IDL.Text,
    'description' : IDL.Text,
    'mentorName' : IDL.Text,
    'price' : IDL.Nat,
    'mentorBio' : IDL.Text,
  });
  const StudentProgress = IDL.Record({
    'progressPercent' : IDL.Nat,
    'royaltiesEarned' : IDL.Nat,
    'courseId' : CourseId,
  });
  const UserProfile = IDL.Record({ 'region' : IDL.Text, 'name' : IDL.Text });
  const HeritageRegion = IDL.Record({
    'artForms' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
  });
  const ArtworkId = IDL.Nat;
  const ArtworkStatus = IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Artwork = IDL.Record({
    'id' : ArtworkId,
    'status' : ArtworkStatus,
    'studentId' : IDL.Principal,
    'submittedAt' : IDL.Nat64,
    'image' : ExternalBlob,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCourse' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'enrollInCourse' : IDL.Func([CourseId], [], []),
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getCallerCoursesProgress' : IDL.Func(
        [],
        [IDL.Opt(IDL.Vec(StudentProgress))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoursesByRegion' : IDL.Func([IDL.Text], [IDL.Vec(Course)], ['query']),
    'getHeritageRegions' : IDL.Func([], [IDL.Vec(HeritageRegion)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVerifiedArtworks' : IDL.Func([], [IDL.Vec(Artwork)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitArtwork' : IDL.Func([ExternalBlob], [], []),
    'verifyArtwork' : IDL.Func([ArtworkId, ArtworkStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };