/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Artwork {
  'id' : ArtworkId,
  'status' : ArtworkStatus,
  'studentId' : Principal,
  'submittedAt' : bigint,
  'image' : ExternalBlob,
}
export type ArtworkId = bigint;
export type ArtworkStatus = { 'verified' : null } |
  { 'pending' : null } |
  { 'rejected' : null };
export interface Course {
  'id' : CourseId,
  'region' : string,
  'title' : string,
  'artType' : string,
  'description' : string,
  'mentorName' : string,
  'price' : bigint,
  'mentorBio' : string,
}
export type CourseId = bigint;
export type ExternalBlob = Uint8Array;
export interface HeritageRegion { 'artForms' : Array<string>, 'name' : string }
export interface StudentProgress {
  'progressPercent' : bigint,
  'royaltiesEarned' : bigint,
  'courseId' : CourseId,
}
export interface UserProfile { 'region' : string, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCourse' : ActorMethod<
    [string, string, string, bigint, string, string, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'enrollInCourse' : ActorMethod<[CourseId], undefined>,
  'getAllCourses' : ActorMethod<[], Array<Course>>,
  'getCallerCoursesProgress' : ActorMethod<[], [] | [Array<StudentProgress>]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCoursesByRegion' : ActorMethod<[string], Array<Course>>,
  'getHeritageRegions' : ActorMethod<[], Array<HeritageRegion>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVerifiedArtworks' : ActorMethod<[], Array<Artwork>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitArtwork' : ActorMethod<[ExternalBlob], undefined>,
  'verifyArtwork' : ActorMethod<[ArtworkId, ArtworkStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];